# This rule is not used by the project pod-monitor-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the monitor.storehub.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-monitor-operator
    app.kubernetes.io/managed-by: kustomize
  name: podmonitor-editor-role
rules:
- apiGroups:
  - monitor.storehub.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.storehub.com
  resources:
  - podmonitors/status
  verbs:
  - get
