apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pod-monitor-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "pod-monitor.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pod-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
